### ISSUE TITLE
ImportError: No module named common

### ISSUE THREAD

**Issue by kwketh** [devttys0/binwalk#124]
Hi all.

After installing binwalk-2.0 via `sudo python setup.py install`, if anyone runs into the following issue:
```
$ binwalk
Traceback (most recent call last):
  File "/usr/bin/binwalk", line 7, in <module>
    from binwalk.common import str2int
ImportError: No module named common
```
There is a conflict when binwalk-1.0 is installed in `/usr/bin/binwalk` prior to installing binwalk-2.x via `sudo python setup.py install`. The binwalk-1.0 located in `/usr/bin/binwalk` imports `binwalk.common`, which no longer exists in the major binwalk-2.0 release.

A quick test to confirm this:
```
$ which binwalk
/usr/bin/binwalk
$ rm /usr/bin/binwalk
$ which binwalk
/usr/local/bin/binwalk
$ binwalk
Binwalk v2.1.0
Craig Heffner, http://www.binwalk.org
... (all works now)
```

From the above we can conclude that deleting the older binwalk-1.0 version will do the trick:
```
rm /usr/bin/binwalk
```

I understand this *seems* more like an issue with packager manager, however what is happening is that binwalk-1.x is loading binwalk-2.x module, and that should not happen. I agree that binwalk-1.0 is outdated and binwalk-2.x should definitely be used over it, however some users that have binwalk-1.0 installed prior to updating (like me) may find it troubling understanding what's going on, as the error thrown is not very clear, rather it throws off the user thinking there is something wrong with installation process. In my case, I have completely forgot I had binwalk-1.0 installed. `binwalk --version` (or just `binwalk`) wouldn't work either so a user couldn't easily confirm which version it is running neither (same error gets thrown when checking version).

Renaming the module `binwalk` to `binwalk2` would resolve the issue, since it is a major release from 1.x and seems to be a reasonable way of dealing with such conflicts. Running `binwalk --version` would then of course continue working and would print `v1.0`, therefore the user would be aware that there is an outdated binwalk installed and that the problem are the paths - not anything else.

I stand that the issue should remain open as it may come up again for some users - and hopefully this answer can save their time digging.

**Comment by devttys0** [comment]
While renaming the module to `binwalk2` would fix issues such as this, I made a conscious decision not to do so when first developing v2, and I think it would be more detrimental/confusing to change it now, almost 1 1/2 years later, even if I wanted to.

Generally speaking, major version changes in a module/library/tool/whatever denote major changes in the code, such as breaking API compatibility, as is the case with binwalk v1 vs v2. Unless there is a specific reason or desire to support the older code base (I had neither), there is really no reason to change the library/module name every time a major change in the code occurs.

Of course, breaking API compatibility is a PITA for users, and results in problems such as this. However, I'd argue that at least in this case, breaking the API was actually a good thing, as it immediately alerted you to a problem, albeit a puzzling one. 

Let's say that the binwalk v2.0 module was installed under the name `binwalk2`, leaving the previously installed `binwalk` module in tact. Everything would have worked properly, and since you didn't know that you already had v1.0 installed, you would have had no reason to specifically check the installed version number, and may not have noticed the version discrepancy for some time. Even once you did notice it, you are now presented with an equally puzzling problem: you downloaded v2.x, but `setup.py` seemingly installed v1.0! Eventually you would have had to perform basically the same troubleshooting steps in order to find that you had two binwalks installed to `/usr/bin` and `/usr/local/bin`, and to delete the older one in `/usr/bin`.

I'm not saying either case is particularly desirable, and I apologize for the confusion as I do try to make my tools easy to use. All I'm saying is that there are advantages and disadvantages to re-naming or not re-naming the module, and I chose the latter.

I have updated the `INSTALL.md` documentation and the wiki FAQ page to suggest running `setup.py uninstall` first when upgrading from older versions of binwalk; this will entirely remove the existing Python module and executable, and would have prevented this issue entirely.

The open issues list should reflect issues that have not yet been resolved, or which need some further action. Since I will not be taking further action on this, I think it is more appropriate to close the issue than to leave it open. The `INSTALL.md` documentation and wiki pages are really better places to document this type of thing anyway, and anyone searching the issue tracking system for problems related to their bug should really be searching all issues, open and closed.
