### ISSUE TITLE
Add API functionality to obtain full output file path for each result

### ISSUE THREAD

**Issue by ddcc** [devttys0/binwalk#135]
Currently, binwalk doesn't provide any API mechanism to obtain the output file path for a given signature match result, because the `extract.conf` file allows any command to be executed with unpredictable effect on the extraction directory state. 

This is problematic in a number of ways, for example, [extractor.py:427](https://github.com/devttys0/binwalk/blob/62e0ae1414a0e8f7c46d5d24c31a7ce8d9d1be45/src/binwalk/modules/extractor.py#L427) attempts to guess at the output file name in order to prevent deletion of a preexisting file, but is not necessarily always correct. Likewise, [extractor.py:450](https://github.com/devttys0/binwalk/blob/62e0ae1414a0e8f7c46d5d24c31a7ce8d9d1be45/src/binwalk/modules/extractor.py#L450) attempts to clean up the output result if it is an empty file, but doesn't account for e.g. an empty `squashfs-root` directory.

In order to resolve this, I propose to add another field to the rule file format in `extract.conf` that can be used to encode the output file name. For example, `%d` could be used to indicate that the output is equivalent to `splitext(%e)[0]`. Any existing commands that use the `%%` placeholder could have the `%%<path>%%` field moved to this new field, and replaced with another placeholder such `%o`. These new rules would be similar to the following examples:
```
^lzma compressed data:7z:%d:7z e -y '%e':0,1
^squashfs filesystem:squashfs:%%squashfs-root%%:unsquashfs -d '%o' '%e':0:False
```

Although this would open up a potential race condition between the pre-existing file check at [extractor.py:427](https://github.com/devttys0/binwalk/blob/62e0ae1414a0e8f7c46d5d24c31a7ce8d9d1be45/src/binwalk/modules/extractor.py#L427) and the actual extraction at [extractor.py:433](https://github.com/devttys0/binwalk/blob/62e0ae1414a0e8f7c46d5d24c31a7ce8d9d1be45/src/binwalk/modules/extractor.py#L433), since the extraction operation is not security sensitive, and these two operations are quite close together, I feel like this is not an issue.

**Comment by devttys0** [comment]
This could work, but I'm hesitant to keep adding things to the rules file, they've already gotten more complex than I ever originally intended. Since binwalk relies on external utilities for most extraction, there is also no guarantee that all future extraction utilities will support an output file/directory option, so I'd rather a more generic solution (granted, this would be unlikely).

The problems mentioned in `extractor.py` are legitimate, but the reason for that code was primarily due to the large number of false positive LZMA results, which resulting in huge numbers of 0-size files. With the (semi-)recent updates which drastically improve LZMA signatures, it is no longer needed.

As such, the `--rm` feature is still available, but it no longer removes 0-size files. It also does not remove the original file if its MD5 hash has changed after running an extractor.

Further, a full list of both carved (i.e., files `dd`'d out of the firmware by binwalk) and extracted (i.e., files created by extraction utilities) are now available via the API (see [the API documentation](https://github.com/devttys0/binwalk/blob/master/API.md) for an example).
