### ISSUE TITLE
Automatic extraction error

### ISSUE THREAD

**Issue by byt3bl33d3r** [devttys0/binwalk#95]
Hi,
whenever I pass the -e argument on a firmware image I get this error
```WARNING: Extractor.execute failed to run external extrator 'unsquashfs -d '%%squashfs-root%%' '%e'': [Errno 2] No such file or directory```
But the filesystem seems to have been extracted anyway.

Big fan btw!

Cheers

**Comment by devttys0** [comment]
Providing that you don't have `unsquashfs` installed, this warning is expected (even if extraction was ultimately successful).

Some file types have multiple extractors; binwalk will try each one until it finds one that works. You will get a warning if binwalk tries to run an extraction utility that doesn't exist, because if the extraction does ultimately fail, you at least know that it may have failed due to not having the correct extraction utility installed.

In this case while you don't have `unsquashfs` installed, you probably do have `sasquatch` installed, which binwalk attempts to use if `unsqaushfs` fails. If `sasquatch` also fails, it will then attempt to mount the SquashFS image.

You can view the extraction rules here: https://github.com/devttys0/binwalk/blob/master/src/binwalk/config/extract.conf#L42.

**Comment by byt3bl33d3r** [comment]
@devttys0 ah thanks! i had ```unsquashfs``` installed just not in $PATH
